# Generated by Django 4.2.9 on 2024-01-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_identification', '0003_remove_profile_email_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/profile-img.png', upload_to='profile_pics'),
        ),
    ]
