# Generated by Django 4.2.9 on 2024-01-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_identification', '0003_remove_profile_email_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
