# Generated by Django 4.2.9 on 2024-02-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_identification', '0011_alter_tree_introduction_alter_tree_tree_habitat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='introduction',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
